# Generated by Django 5.0.3 on 2024-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisconf',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='redisconf',
            name='host',
            field=models.CharField(max_length=255, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='redisconf',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='redisconf',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密码'),
        ),
    ]
