# Generated by Django 5.0.3 on 2024-03-06 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('server', models.CharField(max_length=20, verbose_name='redis名')),
                ('db', models.CharField(max_length=20, verbose_name='db名')),
                ('key', models.CharField(db_index=True, max_length=120, verbose_name='key')),
                ('old_value', models.TextField(verbose_name='old value')),
                ('value', models.TextField(blank=True, null=True, verbose_name='value')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
    ]
