# Generated by Django 5.0.3 on 2024-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationinfo',
            name='key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='operationinfo',
            name='server',
            field=models.CharField(max_length=255, verbose_name='redis名'),
        ),
        migrations.AlterField(
            model_name='operationinfo',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
